"""Machine-readable map of all 11 strategies' scoring rules.

Each entry lists every threshold used by the strategy evaluator in
trade_strategies.py. This is included in the Claude criticizer prompt so it
knows exactly what signals each strategy checks, and serves as the parameter
registry for future automated tuning.

Rules with numeric thresholds have ``param_key`` and ``default`` fields so the
criticizer can reference them in parameter recommendations and the evaluators
can look up runtime overrides.
"""

STRATEGY_RULES: dict[str, dict] = {
    "Short Straddle": {
        "direction": "Neutral",
        "type": "credit",
        "scoring_rules": [
            {"signal": "atm_iv", "condition": "< 15", "score_change": "+25", "description": "Low IV favorable for selling",
             "param_key": "iv_low_threshold", "default": 15},
            {"signal": "atm_iv", "condition": "15-20", "score_change": "+15", "description": "Moderate IV",
             "param_key": "iv_moderate_threshold", "default": 20},
            {"signal": "atm_iv", "condition": ">= 20", "score_change": "-10", "description": "High IV unfavorable"},
            {"signal": "rsi", "condition": "40-60", "score_change": "+20", "description": "Neutral RSI zone",
             "param_key": "rsi_neutral_low", "default": 40},
            {"signal": "rsi", "condition": "40-60", "score_change": "+20", "description": "Neutral RSI zone (upper)",
             "param_key": "rsi_neutral_high", "default": 60},
            {"signal": "rsi", "condition": "30-70", "score_change": "+5", "description": "Moderate RSI",
             "param_key": "rsi_moderate_low", "default": 30},
            {"signal": "rsi", "condition": "30-70", "score_change": "+5", "description": "Moderate RSI (upper)",
             "param_key": "rsi_moderate_high", "default": 70},
            {"signal": "rsi", "condition": "outside 30-70", "score_change": "-15", "description": "Extreme RSI"},
            {"signal": "spot_vs_max_pain", "condition": "< 0.3%", "score_change": "+20", "description": "Spot within 0.3% of max pain",
             "param_key": "max_pain_close_pct", "default": 0.3},
            {"signal": "spot_vs_max_pain", "condition": "0.3-0.8%", "score_change": "+10", "description": "Spot near max pain",
             "param_key": "max_pain_near_pct", "default": 0.8},
            {"signal": "spot_vs_max_pain", "condition": "> 0.8%", "score_change": "-10", "description": "Spot far from max pain"},
            {"signal": "pcr", "condition": "0.8-1.2", "score_change": "+15", "description": "Balanced PCR",
             "param_key": "pcr_neutral_low", "default": 0.8},
            {"signal": "pcr", "condition": "0.8-1.2", "score_change": "+15", "description": "Balanced PCR (upper)",
             "param_key": "pcr_neutral_high", "default": 1.2},
            {"signal": "pcr", "condition": "outside 0.8-1.2", "score_change": "-5", "description": "Skewed PCR"},
            {"signal": "bb_width_pct", "condition": "< 1.0%", "score_change": "+10", "description": "Tight Bollinger Bands",
             "param_key": "bb_width_tight_pct", "default": 1.0},
        ],
    },
    "Short Strangle": {
        "direction": "Neutral",
        "type": "credit",
        "scoring_rules": [
            {"signal": "atm_iv", "condition": "< 18", "score_change": "+20", "description": "Low IV favorable",
             "param_key": "iv_low_threshold", "default": 18},
            {"signal": "atm_iv", "condition": "18-22", "score_change": "+10", "description": "Moderate IV",
             "param_key": "iv_moderate_threshold", "default": 22},
            {"signal": "support_resistance", "condition": "both present", "score_change": "+15", "description": "Strong support and resistance"},
            {"signal": "rsi", "condition": "35-65", "score_change": "+15", "description": "No extreme momentum",
             "param_key": "rsi_neutral_low", "default": 35},
            {"signal": "rsi", "condition": "35-65", "score_change": "+15", "description": "No extreme momentum (upper)",
             "param_key": "rsi_neutral_high", "default": 65},
            {"signal": "spot_in_range", "condition": "between support-resistance", "score_change": "+15", "description": "Spot within band"},
            {"signal": "bb_width_pct", "condition": "< 1.2%", "score_change": "+10", "description": "Compressed BB",
             "param_key": "bb_width_tight_pct", "default": 1.2},
        ],
    },
    "Long Straddle": {
        "direction": "Neutral",
        "type": "debit",
        "scoring_rules": [
            {"signal": "bb_width_pct", "condition": "< 0.8%", "score_change": "+25", "description": "BB squeeze — breakout expected",
             "param_key": "bb_width_squeeze_pct", "default": 0.8},
            {"signal": "bb_width_pct", "condition": "0.8-1.0%", "score_change": "+15", "description": "Moderate BB compression",
             "param_key": "bb_width_moderate_pct", "default": 1.0},
            {"signal": "iv_skew", "condition": "abs > 3", "score_change": "+20", "description": "Significant IV imbalance",
             "param_key": "iv_skew_threshold", "default": 3},
            {"signal": "atm_iv", "condition": "> 18", "score_change": "+10", "description": "Elevated IV implies movement",
             "param_key": "iv_elevated_threshold", "default": 18},
            {"signal": "atm_iv", "condition": "<= 18", "score_change": "-10", "description": "Low IV — no movement expected"},
            {"signal": "rsi", "condition": "45-55", "score_change": "+10", "description": "Coiled RSI ready to break",
             "param_key": "rsi_coiled_low", "default": 45},
            {"signal": "rsi", "condition": "45-55", "score_change": "+10", "description": "Coiled RSI ready to break (upper)",
             "param_key": "rsi_coiled_high", "default": 55},
        ],
    },
    "Long Strangle": {
        "direction": "Neutral",
        "type": "debit",
        "scoring_rules": [
            {"signal": "bb_width_pct", "condition": "< 1.0%", "score_change": "+20", "description": "Breakout setup",
             "param_key": "bb_width_tight_pct", "default": 1.0},
            {"signal": "atm_iv", "condition": "< 16", "score_change": "+20", "description": "Cheap premiums for longs",
             "param_key": "iv_cheap_threshold", "default": 16},
            {"signal": "atm_iv", "condition": "16-20", "score_change": "+10", "description": "Moderate premiums",
             "param_key": "iv_moderate_threshold", "default": 20},
            {"signal": "iv_skew", "condition": "abs > 2", "score_change": "+10", "description": "Directional pressure building",
             "param_key": "iv_skew_threshold", "default": 2},
        ],
    },
    "Bull Put Spread": {
        "direction": "Bullish",
        "type": "credit",
        "scoring_rules": [
            {"signal": "supertrend_direction", "condition": "== 1", "score_change": "+15", "description": "Supertrend bullish"},
            {"signal": "spot_vs_vwap", "condition": "spot > vwap", "score_change": "+15", "description": "Spot above VWAP"},
            {"signal": "ema_alignment", "condition": "ema_9 > ema_21 > ema_50", "score_change": "+10", "description": "Bullish EMA alignment"},
            {"signal": "pcr", "condition": "> 1.2", "score_change": "+15", "description": "Heavy put writing (bullish)",
             "param_key": "pcr_bullish_threshold", "default": 1.2},
            {"signal": "pcr", "condition": "1.0-1.2", "score_change": "+5", "description": "Moderate put writing",
             "param_key": "pcr_moderate_threshold", "default": 1.0},
            {"signal": "rsi", "condition": "< 70", "score_change": "+5", "description": "Not overbought",
             "param_key": "rsi_overbought_threshold", "default": 70},
            {"signal": "rsi", "condition": ">= 70", "score_change": "-10", "description": "Overbought — risk of reversal"},
        ],
    },
    "Bear Call Spread": {
        "direction": "Bearish",
        "type": "credit",
        "scoring_rules": [
            {"signal": "supertrend_direction", "condition": "== -1", "score_change": "+15", "description": "Supertrend bearish"},
            {"signal": "spot_vs_vwap", "condition": "spot < vwap", "score_change": "+15", "description": "Spot below VWAP"},
            {"signal": "ema_alignment", "condition": "ema_9 < ema_21 < ema_50", "score_change": "+10", "description": "Bearish EMA alignment"},
            {"signal": "pcr", "condition": "< 0.7", "score_change": "+15", "description": "Low put writing (bearish)",
             "param_key": "pcr_bearish_threshold", "default": 0.7},
            {"signal": "pcr", "condition": "0.7-1.0", "score_change": "+5", "description": "Moderate call bias",
             "param_key": "pcr_moderate_threshold", "default": 1.0},
            {"signal": "rsi", "condition": "> 30", "score_change": "+5", "description": "Not oversold",
             "param_key": "rsi_oversold_threshold", "default": 30},
            {"signal": "rsi", "condition": "<= 30", "score_change": "-10", "description": "Oversold — risk of bounce"},
        ],
    },
    "Bull Call Spread": {
        "direction": "Bullish",
        "type": "debit",
        "scoring_rules": [
            {"signal": "ema_alignment", "condition": "ema_9 > ema_21 > ema_50", "score_change": "+20", "description": "Bullish EMA alignment"},
            {"signal": "supertrend_direction", "condition": "== 1", "score_change": "+15", "description": "Supertrend bullish"},
            {"signal": "spot_vs_vwap", "condition": "spot > vwap", "score_change": "+10", "description": "Spot above VWAP"},
            {"signal": "rsi", "condition": "50-70", "score_change": "+15", "description": "Bullish momentum, not overbought",
             "param_key": "rsi_bullish_low", "default": 50},
            {"signal": "rsi", "condition": ">= 70", "score_change": "-10", "description": "Overbought",
             "param_key": "rsi_overbought_threshold", "default": 70},
            {"signal": "atm_iv", "condition": ">= 14", "score_change": "-15", "description": "High IV — buying expensive premium",
             "param_key": "iv_high_penalty_threshold", "default": 14},
            {"signal": "bb_width_pct", "condition": ">= 1.5%", "score_change": "-15", "description": "Wide BB — breakout already happened",
             "param_key": "bb_width_expanded_pct", "default": 1.5},
        ],
    },
    "Bear Put Spread": {
        "direction": "Bearish",
        "type": "debit",
        "scoring_rules": [
            {"signal": "ema_alignment", "condition": "ema_9 < ema_21 < ema_50", "score_change": "+20", "description": "Bearish EMA alignment"},
            {"signal": "supertrend_direction", "condition": "== -1", "score_change": "+15", "description": "Supertrend bearish"},
            {"signal": "spot_vs_vwap", "condition": "spot < vwap", "score_change": "+10", "description": "Spot below VWAP"},
            {"signal": "rsi", "condition": "30-50", "score_change": "+15", "description": "Bearish momentum, not oversold",
             "param_key": "rsi_bearish_low", "default": 30},
            {"signal": "rsi", "condition": "30-50", "score_change": "+15", "description": "Bearish momentum (upper)",
             "param_key": "rsi_bearish_high", "default": 50},
            {"signal": "rsi", "condition": "<= 30", "score_change": "-10", "description": "Oversold",
             "param_key": "rsi_oversold_threshold", "default": 30},
            {"signal": "atm_iv", "condition": ">= 14", "score_change": "-15", "description": "High IV — buying expensive premium",
             "param_key": "iv_high_penalty_threshold", "default": 14},
            {"signal": "bb_width_pct", "condition": ">= 1.5%", "score_change": "-15", "description": "Wide BB — breakout already happened",
             "param_key": "bb_width_expanded_pct", "default": 1.5},
        ],
    },
    "Iron Condor": {
        "direction": "Neutral",
        "type": "credit",
        "scoring_rules": [
            {"signal": "rsi", "condition": "40-60", "score_change": "+20", "description": "Perfectly neutral RSI",
             "param_key": "rsi_neutral_low", "default": 40},
            {"signal": "rsi", "condition": "40-60", "score_change": "+20", "description": "Perfectly neutral RSI (upper)",
             "param_key": "rsi_neutral_high", "default": 60},
            {"signal": "rsi", "condition": "35-65", "score_change": "+10", "description": "Near-neutral RSI",
             "param_key": "rsi_moderate_low", "default": 35},
            {"signal": "rsi", "condition": "35-65", "score_change": "+10", "description": "Near-neutral RSI (upper)",
             "param_key": "rsi_moderate_high", "default": 65},
            {"signal": "bb_width_pct", "condition": "< 1.0%", "score_change": "+15", "description": "Tight range",
             "param_key": "bb_width_tight_pct", "default": 1.0},
            {"signal": "atm_iv", "condition": "< 18", "score_change": "+15", "description": "Moderate IV good for selling",
             "param_key": "iv_moderate_threshold", "default": 18},
            {"signal": "pcr", "condition": "0.85-1.15", "score_change": "+10", "description": "Balanced PCR",
             "param_key": "pcr_balanced_low", "default": 0.85},
            {"signal": "pcr", "condition": "0.85-1.15", "score_change": "+10", "description": "Balanced PCR (upper)",
             "param_key": "pcr_balanced_high", "default": 1.15},
            {"signal": "spot_in_range", "condition": "between support-resistance", "score_change": "+10", "description": "Spot in range"},
        ],
    },
    "Long Call (CE)": {
        "direction": "Bullish",
        "type": "debit",
        "scoring_rules": [
            {"signal": "all_bullish", "condition": "ema_bullish + supertrend_1 + spot>vwap", "score_change": "+30", "description": "All signals aligned bullish"},
            {"signal": "ema_alignment", "condition": "ema_9 > ema_21 > ema_50", "score_change": "+10", "description": "Bullish EMA (partial)"},
            {"signal": "supertrend_direction", "condition": "== 1", "score_change": "+10", "description": "Supertrend bullish (partial)"},
            {"signal": "spot_vs_vwap", "condition": "spot > vwap", "score_change": "+5", "description": "Above VWAP (partial)"},
            {"signal": "rsi", "condition": "< 70", "score_change": "+10", "description": "Room to run higher",
             "param_key": "rsi_overbought_threshold", "default": 70},
            {"signal": "rsi", "condition": ">= 70", "score_change": "-15", "description": "Overbought"},
            {"signal": "pcr", "condition": "> 1.2", "score_change": "+10", "description": "Bullish options flow",
             "param_key": "pcr_bullish_threshold", "default": 1.2},
            {"signal": "atm_iv", "condition": ">= 14", "score_change": "-15", "description": "High IV — naked long buying expensive premium",
             "param_key": "iv_high_penalty_threshold", "default": 14},
        ],
    },
    "Long Put (PE)": {
        "direction": "Bearish",
        "type": "debit",
        "scoring_rules": [
            {"signal": "all_bearish", "condition": "ema_bearish + supertrend_-1 + spot<vwap", "score_change": "+30", "description": "All signals aligned bearish"},
            {"signal": "ema_alignment", "condition": "ema_9 < ema_21 < ema_50", "score_change": "+10", "description": "Bearish EMA (partial)"},
            {"signal": "supertrend_direction", "condition": "== -1", "score_change": "+10", "description": "Supertrend bearish (partial)"},
            {"signal": "spot_vs_vwap", "condition": "spot < vwap", "score_change": "+5", "description": "Below VWAP (partial)"},
            {"signal": "rsi", "condition": "> 30", "score_change": "+10", "description": "Room to fall further",
             "param_key": "rsi_oversold_threshold", "default": 30},
            {"signal": "rsi", "condition": "<= 30", "score_change": "-15", "description": "Oversold"},
            {"signal": "pcr", "condition": "< 0.7", "score_change": "+10", "description": "Bearish options flow",
             "param_key": "pcr_bearish_threshold", "default": 0.7},
            {"signal": "atm_iv", "condition": ">= 14", "score_change": "-15", "description": "High IV — naked long buying expensive premium",
             "param_key": "iv_high_penalty_threshold", "default": 14},
        ],
    },
}
